---
language: go
go:
- 1.8.x
- 1.9.x
- 1.10.x
- 1.11.x

install:
- curl -sL https://goo.gl/g1CpPX | bash -s v1.0.2 # Golang dev tools including pre-compiled Ginkgo and other useful tools

script:
- make test
