# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


# [[constraint]]
#   branch = "v2"
#   name = "gopkg.in/yaml.v2"

required = ["gopkg.in/fsnotify.v1"]

[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "=v7.0.0"

[[constraint]]
  name = "k8s.io/helm"
  branch = "release-2.10"


# ignored = [
#    "git.apache.org/thrift.git/lib/go/thrift",
#    "golang.org/x/sys/unix",
# ]
#
# required = ["gopkg.in/fsnotify.v1"]
#
# [[constraint]]
#   name = "k8s.io/helm"
#   version = "2.10.7"
#
# [[constraint]]
#   name = "gopkg.in/fsnotify.v1"
#   source = "https://github.com/fsnotify/fsnotify.git"
#
# [[constraint]]
#   branch = "master"
#   name = "k8s.io/apimachinery"
#
# [[constraint]]
#   name = "k8s.io/client-go"
#   version = "6.0.0"
