# You can initialize minikube "minikube start --cpus 4 --disk-size 100g --memory 8192"
# Make sure helm is up and running, by doing a "helm init --upgrade --force-upgrade"
# The 192.168.99.100 comes from doing a $(minikube ip) from the cmd line
name: minikube
version: 1.0.0
releases:
- chart_name: uaa
  chart_namespace: uaa
  chart_version: 0
  chart_location: "/Users/encalada/Documents/Bluemix/go/src/github.ibm.com/hatch/havener/new-charts/uaa"
  overrides:
    secrets:
      UAA_ADMIN_CLIENT_SECRET: foobar
    env:
      DOMAIN: ((shell minikube ip)).xip.io
    image:
      pullPolicy: "Always"
    kube:
      hostpath_available: true
      external_ips:
      - ((shell dig +short $(minikube ip).xip.io))
      storage_class:
        persistent: "standard"
