name: tomcat deployment
releases:
- chart_name: tomcat-release
  chart_namespace: tomcat
  chart_location: tomcat/stable
  before: [echo "$(date) before release"]
  after: [echo "$(date) after release"]

before:
- cmd: /bin/bash
  args:
  - -c
  - |
    #!/bin/bash

    echo "$(date) before deployment"

after:
- echo "$(date) after deployment"
